title: Tamarack Environmental
email: info@tamarackenvironmental.ca
description: Environmental consulting firm dedicated to sustainable solutions.
baseurl: "/tamarack" # Leave empty if deploying to username.github.io, or set to "/repo-name" for project pages
url: "https://sphericalwave.github.io" # Replace with your GitHub Pages URL
theme: minima # Default theme (optional, we’ll override with custom CSS)
plugins:
  - jekyll-feed